### PR TITLE
Created a python package and a command line interface to pdf-diff

### PR DESCRIPTION
**Pull request by dannylessio**
Dear All,
I've noticed that with small changes pdf-diff can be easily packaged and usable with a command-line interface.
 
With the package the installation become easier, one can install the package simply with: 
` python setup.py install`
and the packages inside the old requirements.txt file are now inside the setup.py file as requirements. 

With a command line script the usage is improved:
`pdf-diff first.pdf second.pdf > comparison.pdf`
and an useful feature like autocompleting pdf names become available.

I have not pushed this changes on PyPi with my name, i hope that this changes will be merged so the owner of this project can do this instead of me.
After the upload of the project on PyPi diff-pdf can be installed without cloning the repository directly by the pip package manager:
`sudo pip install pdf-diff`

Sorry for any mistake on the text, I started not so far writing in English :)
Thank you.

### CODE REVIEW

**Comment by JoshData** [comment]
Neat. Thank you. 

I'm on vacation but will review when I get back. 

On April 2, 2016 9:20:02 PM CDT, Danny Lessio <notifications@github.com> wrote:
>Dear All,
>I've noticed that with small changes pdf-diff can be easily packaged
>and usable with a command-line interface.
> 
>With the package the installation become easier, one can install the
>package simply with: 
>` python setup.py install`
>and the packages inside the old requirements.txt file are now inside
>the setup.py file as requirements. 
>
>With a command line script the usage is improved:
>`pdf-diff first.pdf second.pdf > comparison.pdf`
>and an useful feature like autocompleting pdf names become available.
>
>I have not pushed this changes on PyPi with my name, i hope that this
>changes will be merged so the owner of this project can do this instead
>of me.
>After the upload of the project on PyPi diff-pdf can be installed
>without cloning the repository directly by the pip package manager:
>`sudo pip install pdf-diff`
>
>Sorry for any mistake on the text, I started not so far writing in
>English :)
>Thank you.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/JoshData/pdf-diff/pull/7
>
>-- Commit Summary --
>
>* Created Python package, added command line entry point, updated
>readme.md
>  * Update README.md
>  * Update README.md
>  * Solved entry point issue
>
>-- File Changes --
>
>    M README.md (15)
>    A pdf_diff/__init__.py (0)
>    R pdf_diff/command_line.py (7)
>    D requirements.txt (3)
>    A setup.py (19)
>
>-- Patch Links --
>
>https://github.com/JoshData/pdf-diff/pull/7.patch
>https://github.com/JoshData/pdf-diff/pull/7.diff
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JoshData/pdf-diff/pull/7

-- 
Josh Tauberer (@JoshData) 

// Sent from my phone.

**Comment by JoshData** [comment]
If you could put back some notes on the dependencies (popper, lxml), which you deleted, then it'll be good to go.

**Comment by dannylessio** [comment]
As you can see from setup.py the requirements that i have removed are now here:
```
install_requires=[
          'diff_match_patch_python',
          'lxml',
          'pillow',
      ],
```
So the user has not to worry about these. When he installs pdf-diff with:
`sudo python setup.py install`

If the requirements are not satisfied ( if the python packages are not found in the system ), they will be installed with the pip package manager automatically. 
This should be true for all the operating systems ( not only Ubuntu or OS X ) that have both python3 and pip installed.

Hope to have hit the point, if not please tell me.

Regards,
Danny.

**Comment by JoshData** [comment]
Poppler isn't a Python package. And unless lxml has changed, it requires that libxml-dev be installed first.

**Comment by dannylessio** [comment]
Yes i have now figured out from [here](http://lxml.de/) that lxml is a python binding for the C libraries libxml2 and libxslt so they must be requirements. And i have see that the "poppler" package contains pdftotext as default for all those distributions: [ArchLinux x64](https://www.archlinux.org/packages/extra/i686/poppler/files/), [Ubuntu](https://launchpad.net/ubuntu/+source/poppler) (this contains poppler-utils wich contains pdftotext),  [Debian](https://packages.debian.org/source/wheezy/poppler) (same as Ubuntu), and MacOS.

So, i think that two lines like that:
```
REQUIREMENTS:
libxml2, libxslt, poppler
```
Inside README.md can be enough.
Are you agree with me?

Thank you.

**Comment by JoshData** [comment]
I wish you would just put back my instructions for that. :)

**Comment by dannylessio** [comment]
I have updated requirements according to [this](http://lxml.de/installation.html#requirements) and i have added your OS-specific requirements installation adding "libxslt" on OS X installation because it was missed out.

**Comment by JoshData** [comment]
Cool, merged. :)

**Comment by dannylessio** [comment]
Thank you.

**Comment by dannylessio** [comment]
Thank you, now it would be nice if we can upload this package inside the PyPi package manager.
So the installation becomes easier (sure, if the requirements are satisfied):
`sudo pip install pdf-diff`
without cloning the repository.

I have already a PyPi account, if you want i can do this instead of you.

**Comment by JoshData** [comment]
I've uploaded it to https://pypi.python.org/pypi/pdf-diff.

**Comment by dannylessio** [comment]
Nice :) If you can't find the package through the pip search command this
<https://bitbucket.org/pypa/pypi/issues/397/my-package-doesnt-appear-in-the-search>
is the reason.
Also remember to upload the distruibution using Wheels
<http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#wheels>
.

Thank you :)

2016-04-12 14:10 GMT+02:00 Joshua Tauberer <notifications@github.com>:

**Comment by JoshData** [comment]
Wheels is a project for another day. :)

**Pull request merged**
